# 2. Python에서의 고속 데이터 처리

# 2-2. Numpy 주요 기능 1

## Numpy 모듈 특성 파악

### Numpy 라이브러리

- 다차원, 고속 배열 지원

- 다차원 배열에 대한 직접 연산 지원

    - 반복문 없이 수학적 표현 가능

- 다양한 선형 대수 함수 지원

- 행렬 변환 함수 지원

- 신뢰성 있고 검증된 수치 연산 함수 라이브러리

# 2-3. Numpy 주요 기능 2

## Numpy 행렬과 벡터 개념 이해

### 다차원 벡터 및 행렬 지원

<br/>

V = np.array(\[2, 3, 4\])

- 3개의 원소로 이루어진 벡터

<br/>

M = np.array(\[\[1, 2\], \[3, 4\], \[5, 6\]\])

- 리스트의 리스트 사용, 3x2 행렬

- 3개의 리스트, 각각의 리스트가 2개의 원소 --> 3x2 

<br/>

M = np.array( \[\[1, 2, 3\]\])

- 수학에서 사용하는 행벡터

- 1개 행, 3개의 원소

<br/>

M = np.array(\[\[1\], \[2\], \[3\]\])

- 3x1 행렬(열벡터)

- 3개 행, 각 1개의 원소

<br/>

M = np.array(\[\[1, 2, 3\], \[4, 5, 6\]\]).reshape(3, 2)

- reshape()

- 2x3 행렬 --> 3x2 행렬

- 원소의 개수가 반드시 일치해야 함

<br/>

M = np.array(\[\[1, 2, 3\], \[4, 5, 6\]\]).T

- 행렬에 대한 전체 연산을 위해 transpose 함수 제공

In [7]:
import numpy as np

In [9]:
# 3x3 행렬
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [13]:
# 인덱싱과 슬라이싱을 통해 데이터의 특정 위치 원소 접근
# 쉼표(,)로 분리된 indexing으로 특정 위치의 값을 읽을 수 있다. 
a[1, 1], a[0], a[:, 1], a[1, 1:3]

(5, array([1, 2, 3]), array([2, 5, 8]), array([5, 6]))

### 직접 연산 지원

- 2개 벡터나 행렬에 대한 손쉬운 사칙연산

In [14]:
# 플러스(+) 연산자를 사용한 두 벡터의 합 계산
a = np.array([1, 3, 5, 7, 9])
b = np.array([3, 5, 6, 7, 9])
c = a + b
c

array([ 4,  8, 11, 14, 18])

In [15]:
# 두 행렬의 크기(2x3)가 같기 때문에 + 연산자를 사용해 합 계산
a = np.array([1, 2, 3, 3, 2, 5]).reshape(2, 3)
b = np.array([[-1, -1, -1], [0, 0, 0]])
C = a + b
C

array([[0, 1, 2],
       [3, 2, 5]])

- 연산 시 두 행렬의 데이터 타입은 큰 쪽으로 맞춰지고 두 행렬의 크기가 다른 경우 오류 발생

# 2-4. Numpy 주요 기능 3

### 선형 대수 함수 지원

In [21]:
x = np.array([[1, 2], [4, 5], [6, 7]])
y = np.array([[1, 2], [4, 5]])

x.shape, y.shape

((3, 2), (2, 2))

In [18]:
# matmul() 함수를 이용해 두 행렬간 곱셈
np.matmul(x, y)

array([[ 9, 12],
       [24, 33],
       [34, 47]])

- x와 y에 대한 행렬곱의 결과는 3x2 행렬

- 곱하기(x) 연산자는 2개 행렬 원소 간 곱셈

- matmul() 함수는 행렬의 곱

In [22]:
# 역행렬을 계산하는 inv() 함수
a = np.array([[2, 2, 0], [-2, 1, 1], [3, 0, 1]])
np.linalg.inv(a)

array([[ 0.08333333, -0.16666667,  0.16666667],
       [ 0.41666667,  0.16666667, -0.16666667],
       [-0.25      ,  0.5       ,  0.5       ]])

- inv() 함수는 행과 열의 크기가 같은 정방행렬에만 적용 가능

In [25]:
# 의사역행렬 공식을 활용한 임의의 크기에 대한 역행렬 계산
A = np.array([[1, 2], [2, 4], [3, 6.4]])

np.matmul(np.linalg.inv(np.matmul(A.T, A)), A.T)

array([[ 3.2,  6.4, -5. ],
       [-1.5, -3. ,  2.5]])

![의사역행렬 공식](./img/의사역행렬.PNG)

<br/>

<br/>

### Reference

- https://www.youtube.com/watch?v=-9Er0m0qUOI

- https://www.youtube.com/watch?v=pNuiCE0BrTM

- https://www.youtube.com/watch?v=DjBubVrSQCM