# 2-5. Numpy 주요 기능 활용 실습

## 3. 행렬 연산

### 3-1. 행렬곱

In [2]:
import numpy as np

In [3]:
x = np.array([[1, 2], [4, 5], [6, 7]])
y = np.array([[1, 2], [4, 5]])

print(x)
print(y)
print(np.matmul(x, y))

[[1 2]
 [4 5]
 [6 7]]
[[1 2]
 [4 5]]
[[ 9 12]
 [24 33]
 [34 47]]


In [4]:
x = np.array([[1, 2, 3], [4, 5, 1]])
y = np.array([[1, 2], [4, 5]])

print(x)
print(y)
print(np.matmul(x, y))

[[1 2 3]
 [4 5 1]]
[[1 2]
 [4 5]]


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

In [6]:
x = np.array([[1, 2, 3], [4, 5, 6]])

print(np.matmul(x, x.T))
print(np.matmul(x, np.transpose(x)))

[[14 32]
 [32 77]]
[[14 32]
 [32 77]]


### 3-2. 행렬곱 연산 비교

- 행렬의 고속 연산 기능

    - python의 list와 numpy의 연산 속도 비교

In [7]:
import time

a = np.random.normal(0, 0.1, [500, 500])
b = np.random.normal(0, 0.1, [500, 500])

start_time = time.time()
c = np.matmul(a, b)
print(time.time() - start_time)

0.1391007900238037


In [8]:
def matmul_py(A, B):
    m = len(A)
    n = len(A[0])
    p = len(B[0])
    C = [[0]*p for i in range(m)]

    for i in range(0, m):
        for j in range(0, p):
            for k in range(0, n):
                C[i][j] += A[i][k]*B[k][j]
    return C

In [9]:
A = a.tolist()
B = b.tolist()

start_time = time.time()
matmul_py(A, B)
print(time.time() - start_time)

126.0791699886322


### 3-3. 역행렬

- inv() 함수를 이용해 역행렬 계산하기

In [ ]:
import numpy.linalg as lin

a = np.array([[2, 2, 0], [-2, 1, 1], [3, 0, 1]])
inv = lin.inv(a)

print()