# Numpy 주요 기능 활용 실습

## 2. 기본 연산

### 2-1. 벡터 연산

In [5]:
import numpy as np

In [6]:
a = np.array([1, 3, 5, 7, 9])
b = np.array([3, 5, 6, 7, 9])
c = a + b

print(c)
print(type(c))
print(c.dtype)

[ 4  8 11 14 18]
<class 'numpy.ndarray'>
int32


In [11]:
# 두 벡터 타입이 다른 경우 큰 쪽에 맞춰짐
a = np.array([1, 3, 5, 7, 9])
b = np.array([3, 5, 6, 7, 9.0])
c = a + b
print(c)
print(a.dtype)
print(c.dtype)

[ 4.  8. 11. 14. 18.]
int32
float64


In [12]:
# 반드시 두 행렬의 원소 개수가 동일해야 함
a = np.array([1, 3, 5, 7, 9])
b = np.array([3, 5, 6, 7])
c = a + b

ValueError: operands could not be broadcast together with shapes (5,) (4,) 

In [13]:
# 두 벡터의 내적 계산하기
a = np.array([1, 2, 3, 4, 5])
b = np.array([1, 2, 3, 4, 5])
print(np.sum(a*b))

55


In [15]:
# 두 벡터의 거리 계산하기
p = np.array([2, 2])
q = np.array([3, 7])

(np.sum((p-q)**2))**(0.5)

5.0990195135927845

### 2-2. 행렬 연산

- 행렬에 대해서도 사칙연산 지원

In [16]:
a = np.array([1, 2, 3, 3, 2, 5]).reshape(2, 3)
b = np.array([[-1, 3, 5], [1, 4, 2]])

print(a)
print(b)
print(a+b)

[[1 2 3]
 [3 2 5]]
[[-1  3  5]
 [ 1  4  2]]
[[0 5 8]
 [4 6 7]]


In [17]:
a = np.array([1, 2, 3, 3, 2, 5]).reshape(2, 3)
b = np.array([[-1, -1, -1], [0, 0, 0]])

print(a)
print(b)
print(a*b)

[[1 2 3]
 [3 2 5]]
[[-1 -1 -1]
 [ 0  0  0]]
[[-1 -2 -3]
 [ 0  0  0]]


- 행렬 연산 시 곱하기(*) 연산은 **원소 간 곱**을 의미한다.

In [18]:
# 행렬의 제곱 연산
a = np.array([[1, 2], [3, 4], [5, 6]])
b = a**2
c = a*a

print(b)
print(c)

[[ 1  4]
 [ 9 16]
 [25 36]]
[[ 1  4]
 [ 9 16]
 [25 36]]


<br/>

<br/>

### Reference

- https://www.youtube.com/watch?v=Mb7CLwKd_Zc