# 2-5. Numpy 주요 기능 활용 실습

## Numpy 활용

### 실습 내용

- Numpy 배열 생성, 저장, 로딩

- Numpy 기본 사칙 연산

- Numpy 행렬 연산

- Numpy 브로드캐스팅 연산

- 실제 데이터를 이용한 학습과 예측

In [1]:
import numpy as np
import numpy.linalg as lin
import time

## 1. Numpy array 생성과 저장

### 1-1. Numpy array 생성

In [2]:
# array() 함수를 사용한 배열 객체 a 생성
a = np.array(2.0)
print(a)

2.0


In [3]:
print(type(a))

<class 'numpy.ndarray'>


In [4]:
# shape으로 크기 출력
print(a.shape)

()


In [5]:
if a.shape == ():
    print("차원 0")

차원 0


In [6]:
b = np.array([2.0])

In [7]:
print(b, type(b))

[2.] <class 'numpy.ndarray'>


In [8]:
print(b.shape, f"length: {b.shape[0]}")

(1,) length: 1


In [9]:
# 3개의 원소로 이루어진 객체 c 생성
c = np.array([2, 3, 4])

In [10]:
print(c, c.shape, f"length: {c.shape[0]}")

[2 3 4] (3,) length: 3


In [11]:
# 3x2 행렬 m 생성
m = np.array([[1, 2], [3, 4], [5, 6]])

print(m)
print(m.shape)
print(f"행의 크기: {m.shape[0]}")
print(f"열의 크기: {m.shape[1]}")

[[1 2]
 [3 4]
 [5 6]]
(3, 2)
행의 크기: 3
열의 크기: 2


In [12]:
# 1x3 행벡터 m 생성
m = np.array([[1, 2, 3]])

print(m)
print(m.shape)

[[1 2 3]]
(1, 3)


In [13]:
# 3x1 열벡터 m 생성
m = np.array([[1], [2], [3]])

print(m)
print(m.shape)

[[1]
 [2]
 [3]]
(3, 1)


**Numpy array는 모든 원소의 타입이 동일 하다고 가정**



In [14]:
a = [1, 2.0]        # python list(정수, 실수)
b = np.array([1, 2, 3])     # numpy array(정수)
c = np.array([1, 2, 3.0])   # numpy array(정수, 실수)

# list는 각각의 type을 유지함
print(type(a))
print(type(a[0]))
print(type(a[1]))

# dtype으로 데이터 타입 확인
print(b.dtype)
print(c.dtype)

print(type(c[0]))
print(type(c[2]))

<class 'list'>
<class 'int'>
<class 'float'>
int32
float64
<class 'numpy.float64'>
<class 'numpy.float64'>


- numpy에서는 list 객체 타입을 통해 자동으로 형 결정

- numpy에서는 고속 수치 계산을 위해 단일 데이터 타입을 사용

In [15]:
a = [[1, 2], [3, 4, 5]]
b = np.array([[1, 2], [3, 4, 5]])

print(a)
print(b)

[[1, 2], [3, 4, 5]]
[list([1, 2]) list([3, 4, 5])]


- numpy는 격자 형태의 array 만 지원

### 1-2. array 원소 접근

- 배열 데이터의 특정 위치를 효과적으로 접근할 수 있는 다양한 슬라이싱 표현 제공

In [16]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(a)
print(f"a[0, 0]: ", a[0, 0])        # 1행 1열의 값
print(f"[0]: ", a[0])               # 행렬의 1번째 행의 값
print(f"a[:, 1]: ", a[:, 1])        # 2번째 열의 값
print(f"a[1, 1:3]: ", a[1, 1:3])    # 2행 2열부터 4열의 값

[[1 2 3]
 [4 5 6]
 [7 8 9]]
a[0, 0]:  1
[0]:  [1 2 3]
a[:, 1]:  [2 5 8]
a[1, 1:3]:  [5 6]


In [17]:
i = [0, 2]
b = a[i, :]     # 1번째, 3번째 행의 모든 열 정보
print(b)

[[1 2 3]
 [7 8 9]]


In [18]:
# 범위(시작값, 도착값, 간격 정보)를 지정해 슬라이싱하기
c = np.array([1, 2, 3, 4, 5, 6, 7,  8, 9])
# 0 ~ 7번째 까지 2씩 증가해서 원소 슬라이싱
c[0::2]     

array([1, 3, 5, 7, 9])

In [19]:
a[1:-1]

array([[4, 5, 6]])

In [20]:
a[1:]

array([[4, 5, 6],
       [7, 8, 9]])

In [21]:
# 행이나 열 값 변경
print(a)
a[1, 2] = 7
a[:, 0] = [0, 9, 1]
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[0 2 3]
 [9 5 7]
 [1 8 9]]


In [22]:
# 배열의 일부분을 0으로 만들기
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
print(a)

a[1:-1, 1:-1] = 0
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 1  2  3  4]
 [ 5  0  0  8]
 [ 9  0  0 12]
 [13 14 15 16]]


### 1-3. shape 재구성

- 크기를 재구성하는 T(transpose), reshape 함수

In [23]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[1, 2, 3], [4, 5, 6]]).T
c = np.array([[1, 2, 3], [4, 5, 6]]).transpose()

print(a.shape, b.shape, c.shape)

(2, 3) (3, 2) (3, 2)


In [24]:
# 행벡터를 열벡터로 변경
a = np.array([[1, 2, 3, 4]])
b = np.array([[1, 2, 3, 4]]).T

print(a)
print(b)
print(a.shape, b.shape)

[[1 2 3 4]]
[[1]
 [2]
 [3]
 [4]]
(1, 4) (4, 1)


In [25]:
# 1차원 벡터의 경우
a = np.array([1, 2, 3, 4])
b = np.array([1, 2, 3, 4]).T

print(a)
print(b)
print(a.shape, b.shape)

[1 2 3 4]
[1 2 3 4]
(4,) (4,)


In [26]:
# T는 transpose()의 축약 표현
a = np.array([[1, 2, 3, 4]])
b = np.array([[1, 2, 3, 4]]).transpose()

print(a)
print(b)
print(a.shape, b.shape)

[[1 2 3 4]]
[[1]
 [2]
 [3]
 [4]]
(1, 4) (4, 1)


In [27]:
# reshape() 함수로 임의의 크기로 shape 변경하기
# 원소의 개수가 반드시 일치해야 함
a = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
b = a.reshape(3, 4)

print(a)
print(b)
print(a.shape, b.shape)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(6, 2) (3, 4)


In [28]:
# reshape() 함수를 이용해 1차원 벡터를 2차원 행렬로 변경하기
a = np.array([1, 2, 3, 4, 5, 6])
b = a.reshape(2, 3)

print(a)
print(b)
print(a.shape, b.shape)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
(6,) (2, 3)


In [29]:
# reshape() 함수를 이용해서 열벡터 만들기
a = np.array([[1], [2], [3], [4]])
b = np.array([[1, 2, 3, 4]]).T
c = np.array([1, 2, 3, 4]).reshape(4, 1)
d = np.array([1, 2, 3, 4]).T        # 1차원은 열벡터로 만들 수 없음

print(a)
print(b)
print(c)
print(d)

[[1]
 [2]
 [3]
 [4]]
[[1]
 [2]
 [3]
 [4]]
[[1]
 [2]
 [3]
 [4]]
[1 2 3 4]


### 1-4. 저장과 로딩

- save(), load() 함수를 이용해 파일 저장 및 읽어오기

In [30]:
# save()
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
np.save("a.npy", a)

# load()
b = np.load("a.npy")
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


- csv 파일

- loadtxt() 함수로 csv 파일 로딩

<br/>

<br/>

### Reference

- https://www.youtube.com/watch?v=Mb7CLwKd_Zc