# 2-5. Numpy 주요 기능 활용 실습

## Numpy 활용

### 실습 내용

- Numpy 배열 생성, 저장, 로딩

- Numpy 기본 사칙 연산

- Numpy 행렬 연산

- Numpy 브로드캐스팅 연산

- 실제 데이터를 이용한 학습과 예측

In [1]:
import numpy as np
import numpy.linalg as lin
import time

### 1. Numpy array 생성과 저장

#### 1-1. Numpy array 생성

In [13]:
# array() 함수를 사용한 배열 객체 a 생성
a = np.array(2.0)
print(a)

2.0


In [14]:
print(type(a))

<class 'numpy.ndarray'>


In [15]:
# shape으로 크기 출력
print(a.shape)

()


In [7]:
if a.shape == ():
    print("차원 0")

차원 0


In [8]:
b = np.array([2.0])

In [17]:
print(b, type(b))

[2.] <class 'numpy.ndarray'>


In [19]:
print(b.shape, f"length: {b.shape[0]}")

(1,) length: 1


In [20]:
# 3개의 원소로 이루어진 객체 c 생성
c = np.array([2, 3, 4])

In [21]:
print(c, c.shape, f"length: {c.shape[0]}")

[2 3 4] (3,) length: 3


In [27]:
# 3x2 행렬 m 생성
m = np.array([[1, 2], [3, 4], [5, 6]])

print(m)
print(m.shape)
print(f"행의 크기: {m.shape[0]}")
print(f"열의 크기: {m.shape[1]}")

[[1 2]
 [3 4]
 [5 6]]
(3, 2)
행의 크기: 3
열의 크기: 2


In [29]:
# 1x3 행벡터 m 생성
m = np.array([[1, 2, 3]])

print(m)
print(m.shape)

[[1 2 3]]
(1, 3)


In [30]:
# 3x1 열벡터 m 생성
m = np.array([[1], [2], [3]])

print(m)
print(m.shape)

[[1]
 [2]
 [3]]
(3, 1)


**Numpy array는 모든 원소의 타입이 동일 하다고 가정**



In [39]:
a = [1, 2.0]        # python list(정수, 실수)
b = np.array([1, 2, 3])     # numpy array(정수)
c = np.array([1, 2, 3.0])   # numpy array(정수, 실수)

# list는 각각의 type을 유지함
print(type(a))
print(type(a[0]))
print(type(a[1]))

# dtype으로 데이터 타입 확인
print(b.dtype)
print(c.dtype)

print(type(c[0]))
print(type(c[2]))

<class 'list'>
<class 'int'>
<class 'float'>
int32
float64
<class 'numpy.float64'>
<class 'numpy.float64'>


- numpy에서는 list 객체 타입을 통해 자동으로 형 결정

- numpy에서는 고속 수치 계산을 위해 단일 데이터 타입을 사용

In [40]:
a = [[1, 2], [3, 4, 5]]
b = np.array([[1, 2], [3, 4, 5]])

print(a)
print(b)

[[1, 2], [3, 4, 5]]
[list([1, 2]) list([3, 4, 5])]


--ing

8:40